INVENTORY_TYPES:
  "Chemical Inventory":
    - "chemical_inventory"
    - "chemical_details"
  "General Inventory":
    - "general_inventory"
    - "general_product"
  "Product Inventory (Batch Process)":
    - "batch_inventory"
    - "synthesis"
